# Generated by Django 5.2.1 on 2025-08-29 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(choices=[('1', 'Problema con la cuenta'), ('2', 'Problema con el canal'), ('3', 'Problema con el juego'), ('4', 'Problema con un bot del chat'), ('5', 'Otro')], default='1', max_length=1)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Cerrado')], default='1', max_length=1)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True, null=True)),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True)),
                ('calificacion', models.CharField(blank=True, choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], max_length=1, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_comentario', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
